# Generated by Django 3.2.3 on 2021-05-29 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('original_title', models.CharField(max_length=32)),
                ('original_title_romanised', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('producer', models.CharField(max_length=32)),
                ('release_date', models.IntegerField()),
                ('running_time', models.IntegerField()),
                ('rt_score', models.IntegerField()),
                ('music', models.CharField(max_length=32)),
                ('cover_url', models.URLField()),
                ('wiki_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('avatar_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji_rating', models.IntegerField()),
                ('star_rating', models.IntegerField()),
                ('watched', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show_movies.profile')),
            ],
            options={
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
