# Generated by Django 3.2.3 on 2021-05-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0003_auto_20210529_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=64),
        ),
    ]
