# Generated by Django 3.2.3 on 2021-05-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0004_alter_movies_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='music',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='movies',
            name='original_title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='movies',
            name='original_title_romanised',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
