# Generated by Django 3.2.3 on 2021-05-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0005_auto_20210529_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(max_length=255),
        ),
    ]
