# Generated by Django 3.2.3 on 2021-05-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0006_alter_movies_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='watched',
            field=models.BooleanField(default=True),
        ),
    ]
