# Generated by Django 3.2.3 on 2021-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0007_alter_ratings_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.AddField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(default='Test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(default='Test', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='password',
            field=models.CharField(default='Test', max_length=64),
            preserve_default=False,
        ),
    ]
