# Generated by Django 3.2.3 on 2021-06-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0008_auto_20210602_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='password',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
