# Generated by Django 3.2.3 on 2021-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0009_auto_20210604_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
