# Generated by Django 3.2.3 on 2021-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0010_auto_20210605_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='movies',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
