# Generated by Django 3.2.3 on 2021-05-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0002_alter_movies_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
    ]
