# Generated by Django 3.2.3 on 2021-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_movies', '0003_alter_movies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cover_url',
            field=models.ImageField(blank=True, null=True, upload_to='movies/covers'),
        ),
    ]
